version: '3.1'
services:
  db:
    image: postgres:13.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: john
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    image: 'university:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/john
          - SPRING_DATASOURCE_USERNAME=john
          - SPRING_DATASOURCE_PASSWORD=1234
          - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    restart: always
